services:
  dockapi:
    image: scp-aislider-app:1.0.0-local
    environment:
      - PYTHONPATH=/src
      - PYTHONUNBUFFERED=1
      - PYTHONUTF8=1
      - MY_STAGE=dev
      - MY_VERSION=1.0.0
      - MY_ROOT=
      - MY_NAME=API
      - MY_LOCAL=1
    volumes:
      - .env:/src/.env
      - ./src/app:/src/app
      - ./src/resource:/src/resource
      - ./src/test:/src/test
      - ./secret/aws_config:/root/.aws/config
      - ./secret/aws_credentials:/root/.aws/credentials
      - ./secret/rsa/private_key.pem:/src/rsa/private_key.pem
      - ./secret/rsa/public_key.pem:/src/rsa/public_key.pem
      #- ./docker/entrypoint.sh:/docker/entrypoint.sh
      #- ./docker/gunicorn.conf.py:/docker/gunicorn.conf.py
    ports:
      - 5000:5000
    #entrypoint:
      #- /docker/entrypoint.sh
    #command: gunicorn --log-level=info
    command: python3 -u -X utf8 app/main_api.py
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./database/pgsql/:/docker-entrypoint-initdb.d/
      - ./database/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
#  pgadmin:
#    image: dpage/pgadmin4
#    ports:
#      - "54330:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: 12345
#    volumes:
#      - ./database/pgadmin:/var/lib/pgadmin