AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Parameters:
  MyVersion:
    Type: String
  MyStage:
    Type: String

Resources:
  ALiveWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "scp-aislider-worker-func-${MyStage}"
      PackageType: Image
      ImageUri: !Sub ".dkr.ecr.ap-northeast-2.amazonaws.com/scp-aislider-app:${MyVersion}-${MyStage}"
      ImageConfig:
        WorkingDirectory: "/src"
        EntryPoint:
          - "/usr/local/bin/python"
          - "-m"
          - "awslambdaric"
        Command:
          - "app/main_worker.lambda_handler"
      MemorySize: 1024
      EphemeralStorage:
        Size: 1024
      Timeout: 60
      EventInvokeConfig:
        MaximumRetryAttempts: 1
      Architectures:
        - arm64 # x86_64 arm64
      Environment:
        Variables:
          PYTHONPATH: "/src"
          PYTHONUNBUFFERED: 1
          PYTHONUTF8: 1
          MY_STAGE: !Ref MyStage
          MY_VERSION: !Ref MyVersion
          MY_ROOT: !Sub "/${MyStage}"
          MY_NAME: "WORKER"
          AWS_PROFILE: "default"
          AWS_CONFIG_FILE: "/src/.aws/config"
      FileSystemConfigs:
        - Arn: arn:aws:elasticfilesystem:us-east-2::access-point/fsap
          LocalMountPath: /mnt/slides
      Role: !Sub "arn:aws:iam:::role/scp-aislider-worker-role-${MyStage}"
