version: 2.1
executors:
  executor:
    environment:
      DOCKER_IMAGE: my_aidecipher_server
      DOCKER_FILE_PATH: ./docker/Dockerfile
      DOCKER_FILE_LOCAL_PATH: ./docker/Dockerfile.local

jobs:
  local-job:
    executor: executor
    machine: true
    steps:
    - run:
        name: Set Hash
        command: |
          export COMMIT_HASH=`echo $CIRCLE_SHA1 | head -c 7`
          echo "export COMMIT_HASH=$COMMIT_HASH"
          export abbrev=`echo $CIRCLE_SHA1 | head -c 7`
          echo "export abbrev=$abbrev" >> $BASH_ENV
    - run:
        name: Debug
        command: |
          echo "COMMIT HASH : $COMMIT_HASH"
          echo "COMMIT HASH : $BASH_ENV"
          echo "Docker ID : $DOCKER_ID"
    - run:
        name: Login
        command: |
          echo $DOCKER_PW | docker login -u $DOCKER_ID --password-stdin
    - checkout
    - run:
        name: Build Image
        command: |
          docker build . -t $DOCKER_IMAGE:1.0.0-local -f $DOCKER_FILE_LOCAL_PATH --build-arg MY_TEST=테스트

workflows:
  local-workflow:
    jobs:
    - local-job:
        context: image-build
        filters:
          branches:
            only: main
          tags:
            only: /^local.*/